spring.datasource.url= jdbc:mysql://root:ZRQHaVrLGNrOoxSVTNNXUFflgYXYMdAz@switchback.proxy.rlwy.net:42369/railway
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=ZRQHaVrLGNrOoxSVTNNXUFflgYXYMdAz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

app.jwt.secret=${JWT_SECRET:career-backend-super-secret-key-change-in-production-2026}
app.jwt.expiration-minutes=${JWT_EXPIRY_MINUTES:120}